# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mnURpP-maa7RniR0P2ewsp_KIJUvHHXJ
"""

import pyttsx3
import speech_recognition as sr
from googletrans import Translator

# Инициализация голосового движка
engine = pyttsx3.init()

# Инициализация объекта распознавания речи
recognizer = sr.Recognizer()

# Инициализация переводчика
translator = Translator()

# Функция для преобразования текста в речь
def speak(text):
    engine.say(text)
    engine.runAndWait()

# Функция для распознавания речи
def listen():
    with sr.Microphone() as source:
        print("Скажите текст для перевода:")
        audio = recognizer.listen(source)
        try:
            text = recognizer.recognize_google(audio, language="ru-RU")
            return text
        except sr.UnknownValueError:
            print("Не удалось распознать речь")
        except sr.RequestError as e:
            print(f"Ошибка {e}")

# Функция перевода текста
def translate_text(text, dest_lang):
    translation = translator.translate(text, dest=dest_lang).text
    return translation

# Основной код
if name == "__main__":
    speak("Привет! Я переводчик. Готов перевести вашу речь.")
    speak("На какой язык вы хотите перевести?")
    destination_language = listen()

    while destination_language not in translator.LANGUAGES.keys():
        speak("Извините, я не могу перевести на этот язык. Пожалуйста, выберите другой язык.")
        destination_language = listen()

    speak("Отлично! Говорите текст для перевода.")
    original_text = listen()
    translation_text = translate_text(original_text, destination_language)

    speak("Перевод:")
    speak(translation_text)

pip install speech_recognition

pip install pyttsx3